USE [master]
GO

/****** Object:  Database [Projekt]    Script Date: 25.06.2020 14:00:16 ******/
CREATE DATABASE [Projekt]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Projekt', FILENAME = N'C:\Users\karol\Projekt.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Projekt_log', FILENAME = N'C:\Users\karol\Projekt_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Projekt].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Projekt] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Projekt] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Projekt] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Projekt] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Projekt] SET ARITHABORT OFF 
GO

ALTER DATABASE [Projekt] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Projekt] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Projekt] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Projekt] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Projekt] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Projekt] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Projekt] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Projekt] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Projekt] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Projekt] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Projekt] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Projekt] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Projekt] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Projekt] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Projekt] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Projekt] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Projekt] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Projekt] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Projekt] SET  MULTI_USER 
GO

ALTER DATABASE [Projekt] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Projekt] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Projekt] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Projekt] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Projekt] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Projekt] SET QUERY_STORE = OFF
GO

USE [Projekt]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [Projekt] SET  READ_WRITE 
GO

